import { NextRequest, NextResponse } from 'next/server'
import { getUserIdFromRequest } from '@/lib/auth-server'

interface Transaction {
  transaction_date: string
  amount: number
  description: string
  type: 'INVOICE' | 'RECEIPT' | 'ADJUSTMENT'
  reference_number?: string
  gst_hst_rate?: number
  vendor_name?: string
}

// Simple HTML to PDF conversion using a basic HTML template
function generatePDFHTML(
  transactions: Transaction[],
  importedCount: number,
  timestamp: string
): string {
  const totalAmount = transactions.reduce((sum, t) => sum + t.amount, 0)
  const invoices = transactions.filter(t => t.type === 'INVOICE').length
  const receipts = transactions.filter(t => t.type === 'RECEIPT').length
  const adjustments = transactions.filter(t => t.type === 'ADJUSTMENT').length

  const rows = transactions
    .map(
      (t) => `
    <tr>
      <td style="border: 1px solid #ddd; padding: 10px; font-size: 12px;">${t.transaction_date}</td>
      <td style="border: 1px solid #ddd; padding: 10px; font-size: 12px;">${t.vendor_name || 'N/A'}</td>
      <td style="border: 1px solid #ddd; padding: 10px; font-size: 12px;">${t.description}</td>
      <td style="border: 1px solid #ddd; padding: 10px; font-size: 12px; text-align: center;">
        <span style="background-color: ${t.type === 'INVOICE' ? '#dbeafe' : t.type === 'RECEIPT' ? '#dcfce7' : '#fef3c7'}; padding: 4px 8px; border-radius: 4px; font-size: 11px; font-weight: bold;">
          ${t.type}
        </span>
      </td>
      <td style="border: 1px solid #ddd; padding: 10px; font-size: 12px; text-align: right;">$${t.amount.toFixed(2)}</td>
      <td style="border: 1px solid #ddd; padding: 10px; font-size: 12px; text-align: center;">${t.gst_hst_rate ? t.gst_hst_rate + '%' : '-'}</td>
      <td style="border: 1px solid #ddd; padding: 10px; font-size: 12px; text-align: right;">${t.reference_number || '-'}</td>
    </tr>
  `
    )
    .join('')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Bulk Import Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
      color: #333;
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
      border-bottom: 2px solid #2563eb;
      padding-bottom: 20px;
    }
    h1 {
      color: #1e40af;
      margin: 0;
      font-size: 28px;
    }
    .timestamp {
      color: #666;
      font-size: 12px;
      margin-top: 5px;
    }
    .summary {
      display: grid;
      grid-template-columns: 1fr 1fr 1fr 1fr;
      gap: 15px;
      margin-bottom: 30px;
    }
    .summary-card {
      background-color: #f3f4f6;
      padding: 15px;
      border-radius: 8px;
      border-left: 4px solid #2563eb;
    }
    .summary-label {
      color: #666;
      font-size: 12px;
      font-weight: bold;
      text-transform: uppercase;
      margin-bottom: 5px;
    }
    .summary-value {
      font-size: 24px;
      font-weight: bold;
      color: #1e40af;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }
    th {
      background-color: #2563eb;
      color: white;
      padding: 12px;
      text-align: left;
      font-size: 13px;
      font-weight: bold;
    }
    tr:nth-child(even) {
      background-color: #f9fafb;
    }
    .footer {
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      color: #666;
      font-size: 11px;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📊 Bulk Import Report</h1>
    <div class="timestamp">Generated: ${timestamp}</div>
  </div>

  <div class="summary">
    <div class="summary-card">
      <div class="summary-label">Total Imported</div>
      <div class="summary-value">${importedCount}</div>
    </div>
    <div class="summary-card">
      <div class="summary-label">Total Amount</div>
      <div class="summary-value">$${totalAmount.toFixed(2)}</div>
    </div>
    <div class="summary-card">
      <div class="summary-label">Invoices</div>
      <div class="summary-value">${invoices}</div>
    </div>
    <div class="summary-card">
      <div class="summary-label">Receipts</div>
      <div class="summary-value">${receipts}</div>
    </div>
  </div>

  <h2 style="color: #1e40af; margin-top: 30px;">Transaction Details</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Vendor</th>
        <th>Description</th>
        <th>Type</th>
        <th>Amount</th>
        <th>Tax Rate</th>
        <th>Reference</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>

  <div class="footer">
    <p>This report was automatically generated by Bookkeeping App bulk import feature.</p>
    <p>For support, contact: support@bookkeepingapp.com</p>
  </div>
</body>
</html>
  `
}

export async function POST(request: NextRequest) {
  try {
    // Extract user ID from Authorization header
    const userId = getUserIdFromRequest(request)
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const transactions = body.transactions as Transaction[]
    const importedCount = body.importedCount as number

    if (!Array.isArray(transactions) || typeof importedCount !== 'number') {
      return NextResponse.json(
        { error: 'Invalid request: missing transactions or importedCount' },
        { status: 400 }
      )
    }

    const timestamp = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      timeZoneName: 'short',
    })

    const htmlContent = generatePDFHTML(transactions, importedCount, timestamp)

    // Return HTML that can be printed to PDF by the client
    return new NextResponse(htmlContent, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="bulk-import-${Date.now()}.html"`,
      },
    })
  } catch (error) {
    console.error('Error generating PDF:', error)
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    )
  }
}
