import { NextRequest, NextResponse } from 'next/server'
import { getUserIdFromRequest } from '@/lib/auth-server'

export async function POST(request: NextRequest) {
  try {
    const userId = getUserIdFromRequest(request)
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await request.json()
    const { transactions = [], importedCount = 0 } = body

    // Generate HTML report
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Bulk Import Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; }
    h1 { color: #1e40af; }
    .summary { background: #f0f9ff; padding: 15px; border-radius: 8px; margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #1e40af; color: white; padding: 10px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #ddd; }
    tr:nth-child(even) { background: #f9fafb; }
    .amount { text-align: right; }
    .date { color: #666; }
    .footer { margin-top: 30px; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <h1>Bulk Import Report</h1>
  <p>Generated: ${new Date().toLocaleString()}</p>

  <div class="summary">
    <strong>✓ Import Summary</strong><br>
    Documents Analyzed: <strong>${importedCount}</strong><br>
    Transactions Imported: <strong>${transactions.length}</strong>
  </div>

  ${transactions.length > 0 ? `
  <h2>Imported Transactions</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Vendor</th>
        <th class="amount">Amount</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      ${transactions.map((tx: any) => `
        <tr>
          <td class="date">${tx.transaction_date || 'N/A'}</td>
          <td>${tx.description || 'Unknown'}</td>
          <td>${tx.vendor_name || '-'}</td>
          <td class="amount">$${(tx.amount || 0).toFixed(2)}</td>
          <td>${tx.type || 'RECEIPT'}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="summary">
    <strong>Total Amount:</strong> $${transactions.reduce((sum: number, tx: any) => sum + (tx.amount || 0), 0).toFixed(2)}
  </div>
  ` : '<p>No transactions to display.</p>'}

  <div class="footer">
    <p>This report was generated by the Bookkeeping App bulk import feature.</p>
  </div>
</body>
</html>
    `

    // Return as HTML file (browser will download)
    return new NextResponse(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="bulk-import-${Date.now()}.html"`,
      },
    })
  } catch (error) {
    console.error('PDF export error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to generate report' },
      { status: 500 }
    )
  }
}
